### ISSUE TITLE
Update coloring to something like this

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#10]
![image](https://user-images.githubusercontent.com/11865/79012797-bc71aa80-7b99-11ea-9041-4e302a8513c0.png)

**Comment by strogonoff** [comment]
https://github.com/glossarist/iev-demo-site/commit/cd9ce7b3e5ce3642b099c3e8137007fd311c5868

**Comment by ronaldtse** [comment]
Thanks @strogonoff !
