### ISSUE TITLE
AsciiMath rendering doesn’t support full AsciiMath markup capabilities

### ISSUE THREAD

**Issue by strogonoff** [glossarist/iev-demo-site#11]
Example: https://iev-staging.geolexica.org/concepts/103-07-13/

**Comment by strogonoff** [comment]
Potential replacements: https://github.com/FabianHenneke/jekyll-mathjax-csp or client-side rendering with MathJax

**Comment by strogonoff** [comment]
This seems unlikely to be done by the demo. The abovementioned plugin conflicts with jekyll-asciidoc, and rolling our own rendering will take a bit longer.

**Comment by ronaldtse** [comment]
@strogonoff how are you rendering the math now? Why does math get rendered as HTML?

Are you using the `asciimath` gem? It has an option to render MathML directly. If we embed MathML, the pages will show properly given MathJax is loaded.

**Comment by ronaldtse** [comment]
https://github.com/asciidoctor/asciimath

```ruby
parsed_expression = AsciiMath.parse(asciimath)
math_ml = parsed_expression.to_mathml
```

**Comment by ronaldtse** [comment]
Switched to MathML in https://github.com/riboseinc/jekyll-asciimath/commit/9d2797eef0baf11eaa6ee30d048af9d95d5a649f .

Need to add MathJAX, seems easy enough here:
http://sgeos.github.io/github/jekyll/2016/08/21/adding_mathjax_to_a_jekyll_github_pages_blog.html

**Comment by strogonoff** [comment]
> seems easy enough here 

That one is for client-side rendering. We could do that, but a proper and more accessible solution would be rendering it server-side. We would just use JS/Node implementation instead of Ruby for that.

**Comment by strogonoff** [comment]
Thinking switching to this approach with jekyll-asciidoc, and stopping using jekyll-asciimath: https://github.com/asciidoctor/jekyll-asciidoc#adding-the-stem-assets-to-the-page

**Comment by skalee** [comment]
Could it be fixed in AsciiMath 2.0?

**Comment by ronaldtse** [comment]
@skalee I think this is mostly fixed (we reported many issues to asciimath gem because of this) but maybe there are still issues, let's close this for now and reopen when we see new failures.

**Comment by skalee** [comment]
Sounds good to me. This particular issue is too generic indeed.
