### ISSUE TITLE
Remove date from "All Concepts" page

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#14]
<img width="702" alt="Screen Shot 2020-04-13 at 8 10 14 PM" src="https://user-images.githubusercontent.com/11865/79119375-ca564400-7dc2-11ea-8b99-ed6e90b01df4.png">

**Comment by skalee** [comment]
What about "about" page (https://iev-staging.geolexica.org/about/)? I suppose the same story, but I'd like to confirm that.

![Zrzut ekranu 2020-05-23 o 03 17 39](https://user-images.githubusercontent.com/154287/82718652-0f17a980-9ca4-11ea-9217-eb0d0732908e.png)

**Comment by strogonoff** [comment]
Let’s reopen an issue if it’s not resolved as per original description, and file a new issue otherwise — https://github.com/glossarist/iev-demo-site/issues/24
