### ISSUE TITLE
Language codes shown in Concept page should respect code case

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#16]
> Language codes (alpha-2 or alpha-3) shall be lower case letters for conformity with ISO 639: http://www.loc.gov/standards/iso639-2/php/code_list.php.
> It is the country codes that are capital letters as per ISO 3166.

<img width="1101" alt="Screen Shot 2020-04-14 at 11 48 48 PM" src="https://user-images.githubusercontent.com/11865/79245285-7de63380-7eaa-11ea-9d9b-102a4308cb21.png">

We should not capitalize language codes on all pages.

**Comment by skalee** [comment]
For the reference, it is already fixed in geolexica-server upstream (https://github.com/geolexica/geolexica-server/issues/41).
