### ISSUE TITLE
Implement Concept YAML output

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#20]
@skalee it would be great to have a Concept YAML output that we can use for machine-readability!

**Comment by ronaldtse** [comment]
Ping @skalee , @w00lf will need this for https://github.com/metanorma/metanorma/issues/75 .

**Comment by skalee** [comment]
Almost forgot about this one. Yes, this can be done now.

Just remember that we don't have proper validations on our YAML structures yet, hence produced YAMLs are potentially inconsistent and subject to breaking changes, especially when it comes to what values are allowed in enum fields. For example, I suppose that `entry_status` values will be in lower case in future (`Standard` => `standard`).
