### ISSUE TITLE
Statistics page languages shows empty languages

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#5]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/11865/79012144-2e48f480-7b98-11ea-9e2d-8599264cfb90.png">

Need to update `_data/lang.yaml`

**Comment by strogonoff** [comment]
Fixed last remaining two in https://github.com/glossarist/iev-demo-site/commit/cd5c0c67209ba85cb032e179309062c62afdd875, https://github.com/glossarist/iev-demo-site/commit/1b4a0a1af06921dd34abd7d87c532425a1294496
