### ISSUE TITLE
Concept name/listing should allow math (between `$$...$$`)

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#6]
<img width="760" alt="Screen Shot 2020-04-11 at 2 00 42 AM" src="https://user-images.githubusercontent.com/11865/79012239-71a36300-7b98-11ea-8d42-00b9786ee66b.png">

**Comment by strogonoff** [comment]
Math is showing in concept details page (https://github.com/glossarist/iev-demo-site/commit/5905c795ae6b5d4a5adab1dbf7037955b7856ba9) and concept list (https://github.com/strogonoff/geolexica-server/commit/69ec0c31648e464e2757d6d53fbdfd1b0d3276e6)
