### ISSUE TITLE
Concept page should display math (designation, body, notes, examples)

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#7]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/11865/79012259-7ec05200-7b98-11ea-876d-50e9d608c25e.png">

**Comment by ronaldtse** [comment]
Also the HTML title.

**Comment by strogonoff** [comment]
Math is showing in concept details page (https://github.com/glossarist/iev-demo-site/commit/5905c795ae6b5d4a5adab1dbf7037955b7856ba9) and concept list (https://github.com/strogonoff/geolexica-server/commit/69ec0c31648e464e2757d6d53fbdfd1b0d3276e6).

For more complete math support, https://github.com/glossarist/iev-demo-site/issues/11
