### ISSUE TITLE
Create pages for browsing "per part"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-demo-site#9]
IEV allows this:
![image](https://user-images.githubusercontent.com/11865/79012392-c2b35700-7b98-11ea-8970-705f182098d1.png)

We should provide this too.

**Comment by strogonoff** [comment]
Domains (areas) are supported via a Jekyll collection, awaiting push/deployment & complete index of areas added as `_domains/{{ area ID }}.adoc`.

**Comment by strogonoff** [comment]
Done in https://github.com/glossarist/iev-demo-site/commit/cc472b30cbb6a2920fdcbf18e4e4301ee7a8c97d

Will add all subject areas under `_domains/` collection in a bit.
